// Program curriculum, rendered by the Curriculum section. Each phase lists its modules,
// hands-on labs and projects in the exact order they're taught.
export type CurriculumModule = { type: "module"; title: string; topics: string[] };
export type Lab = { type: "lab"; number: number; title: string };
export type Project = { type: "project"; title: string; scenario: string; includes: string[] };
export type PhaseItem = CurriculumModule | Lab | Project;

export type Phase = {
  title: string;
  items: PhaseItem[];
};

export const modulesOf = (p: Phase) => p.items.filter((i): i is CurriculumModule => i.type === "module");
export const labsOf = (p: Phase) => p.items.filter((i): i is Lab => i.type === "lab");
export const projectsOf = (p: Phase) => p.items.filter((i): i is Project => i.type === "project");

export const curriculum: Phase[] = [
  {
    title: "Production Software & Data Engineering",
    items: [
      {
        type: "module",
        title: "What is a Forward Deployed Engineer?",
        topics: ["FDE Role", "FDE Responsibilities", "FDE Mindset"],
      },
      {
        type: "module",
        title: "Python Fundamentals",
        topics: [
          "Python Basics",
          "Control Flow",
          "Data Structures",
          "Functions",
          "Modules & Packages",
          "Working with Data",
          "Error Handling",
          "API Basics",
          "Object-Oriented Programming",
        ],
      },
      {
        type: "module",
        title: "Python Advanced",
        topics: [
          "Python Project Development",
          "Pydantic",
          "FastAPI",
          "Debugging & Logging",
          "Advanced Python Concepts",
          "Async Programming",
        ],
      },
    ],
  },
  {
    title: "Applied AI I: LLM + RAG",
    items: [
      {
        type: "module",
        title: "LLM Engineering",
        topics: [
          "LLM fundamentals",
          "Tokens",
          "Context windows",
          "Transformers — conceptual understanding",
          "Embeddings",
          "Inference",
          "Model capabilities",
          "Open vs proprietary models",
        ],
      },
      {
        type: "module",
        title: "LLM APIs",
        topics: [
          "API calls",
          "Streaming",
          "Structured output",
          "Function calling",
          "Tool calling",
          "Error handling",
          "Model fallback",
        ],
      },
      {
        type: "module",
        title: "Prompt & Context Engineering",
        topics: [
          "System prompts",
          "User prompts",
          "Few-shot prompting",
          "Structured prompts",
          "Output schemas",
          "Prompt versioning",
          "Prompt testing",
          "Context engineering",
          "Prompt optimization",
          "Treat prompts as code",
          "Regression test prompts",
        ],
      },
      {
        type: "module",
        title: "Model Selection",
        topics: ["Decision Factors", "Model selection lab"],
      },
      {
        type: "module",
        title: "RAG Engineering",
        topics: ["Fundamentals", "Advanced RAG", "Enterprise RAG", "AI Evaluation", "AI Guardrails"],
      },
      { type: "lab", number: 7, title: "Northstar AI Support Copilot" },
      { type: "lab", number: 8, title: "RAG Failure Lab" },
      { type: "lab", number: 9, title: "AI Red-Team Lab" },
    ],
  },
  {
    title: "Applied AI II: Agents & MCP",
    items: [
      {
        type: "module",
        title: "Workflows vs Agents",
        topics: [
          "What is an agent?",
          "What is a workflow?",
          "Agent vs chatbot",
          "Agent vs deterministic workflow",
          "When to use an agent",
          "When NOT to use an agent",
          "Reliability vs flexibility",
        ],
      },
      {
        type: "module",
        title: "Agent Architecture",
        topics: [
          "Tool calling",
          "State",
          "Memory",
          "Planning",
          "ReAct",
          "Router",
          "Planner/executor",
          "Supervisor",
          "Sequential agents",
          "Parallel agents",
          "Multi-agent systems",
          "Human-in-the-loop",
        ],
      },
      {
        type: "module",
        title: "LangGraph",
        topics: [
          "Graph architecture",
          "State",
          "Nodes",
          "Edges",
          "Conditional routing",
          "Persistence",
          "Human approval",
          "Error recovery",
          "Retry",
          "Agent evaluation",
        ],
      },
      {
        type: "module",
        title: "MCP",
        topics: [
          "MCP fundamentals",
          "MCP architecture",
          "MCP client",
          "MCP server",
          "Tools",
          "Resources",
          "Prompts",
          "Tool schemas",
          "Authentication",
          "Authorization",
          "Secure tool execution",
        ],
      },
      {
        type: "module",
        title: "Enterprise Agent Integration",
        topics: ["CRM", "Jira", "Slack", "PostgreSQL", "Email", "REST APIs", "SOAP", "Knowledge base"],
      },
      { type: "lab", number: 10, title: "Northstar Support Agent" },
      { type: "lab", number: 11, title: "MCP Enterprise Tools" },
      { type: "lab", number: 12, title: "Agent Failure Lab" },
      {
        type: "project",
        title: "Autonomous Business Operations Agent",
        scenario: "Automate support operations.",
        includes: [
          "Agent",
          "RAG",
          "MCP",
          "Enterprise tools",
          "Human approval",
          "Security",
          "Evaluation",
          "Observability",
          "Failure handling",
        ],
      },
      {
        type: "module",
        title: "Enterprise Data",
        topics: ["SQL", "Database Investigation", "Data Modeling"],
      },
      {
        type: "module",
        title: "Data Engineering for FDEs",
        topics: [
          "ETL",
          "ELT",
          "Data ingestion",
          "Data validation",
          "Data cleaning",
          "Deduplication",
          "Schema mapping",
          "Data transformation",
          "Batch processing",
          "Data pipelines",
          "Failure recovery",
          "PySpark",
          "Distributed data processing",
          "dbt concepts",
          "Data warehouse concepts",
        ],
      },
      { type: "lab", number: 1, title: "Northstar Data Archaeology" },
      { type: "lab", number: 2, title: "Northstar Data Pipeline" },
      {
        type: "module",
        title: "Git & GitHub Basics",
        topics: ["Git Fundamentals", "Working with Changes", "Branching", "Remote Repository"],
      },
      {
        type: "module",
        title: "Networking Basics",
        topics: [
          "Networking Fundamentals I: Physical Connectivity & Network Types",
          "Networking Fundamentals II: Device Identification & Core Protocols",
          "Networking Fundamentals III: OSI Model & Data Communication",
          "IP Address Fundamentals",
          "Subnetting & CIDR",
          "Gateway & Practical IP Addressing",
          "TCP & UDP",
          "DNS",
          "Network Troubleshooting",
        ],
      },
      {
        type: "module",
        title: "Linux Basics",
        topics: [
          "Introduction to UNIX & Linux",
          "Linux Architecture",
          "Environment Setup",
          "Linux terminal and shell concepts",
          "Essential Linux Commands",
        ],
      },
      {
        type: "module",
        title: "Web & APIs",
        topics: ["Web Fundamentals", "HTML Basics", "CSS Basics", "JavaScript Basics"],
      },
    ],
  },
  {
    title: "Backend & Enterprise Integration",
    items: [
      {
        type: "module",
        title: "Production API Engineering",
        topics: [
          "REST API design",
          "API contracts",
          "OpenAPI",
          "Authentication",
          "Authorization",
          "OAuth2",
          "JWT",
          "RBAC",
          "Multi-tenancy",
          "Pagination",
          "Rate limiting",
          "Retries",
          "Timeouts",
          "Idempotency",
          "API versioning",
          "Webhooks",
        ],
      },
      {
        type: "module",
        title: "Enterprise Integration",
        topics: [
          "REST APIs",
          "SOAP",
          "XML",
          "Webhooks",
          "Third-party APIs",
          "Legacy systems",
          "CRM systems",
          "Ticketing systems",
          "Slack-style integrations",
          "Database integrations",
          "Integration Patterns",
        ],
      },
      {
        type: "module",
        title: "State & Event-Driven Systems",
        topics: [
          "Order and Workflow State",
          "Messaging Infrastructure",
          "Event-Driven Basics",
          "Kafka Basics",
        ],
      },
      { type: "lab", number: 3, title: "Northstar Orders API" },
      { type: "lab", number: 4, title: "Real-Time Order System" },
      { type: "lab", number: 5, title: "Enterprise Integration Challenge" },
    ],
  },
  {
    title: "Frontend & Operational Applications",
    items: [
      {
        type: "module",
        title: "Frontend for FDEs",
        topics: ["React", "API Integration", "Authentication", "Authorization", "Error Handling"],
      },
      {
        type: "module",
        title: "Operational Dashboards",
        topics: [
          "Dashboard Fundamentals",
          "Business Views",
          "Real-Time Operations",
          "Role-Based Operations",
        ],
      },
      { type: "lab", number: 6, title: "Northstar Operations Dashboard" },
    ],
  },
  {
    title: "Cloud, DevOps & LLMOps",
    items: [
      {
        type: "module",
        title: "Docker",
        topics: [
          "Docker images",
          "Containers",
          "Dockerfiles",
          "Multi-container applications",
          "Networking",
          "Volumes",
          "Secrets",
          "Container security",
          "Production hardening",
        ],
      },
      {
        type: "module",
        title: "AWS",
        topics: [
          "IAM",
          "VPC",
          "Networking",
          "EC2",
          "ECS",
          "RDS",
          "S3",
          "Load Balancer",
          "CloudWatch",
          "Secrets Manager",
        ],
      },
      {
        type: "module",
        title: "Terraform",
        topics: [
          "Infrastructure as Code",
          "Providers",
          "Resources",
          "Variables",
          "Outputs",
          "State",
          "Modules",
          "Environment management",
        ],
      },
      {
        type: "module",
        title: "CI/CD",
        topics: [
          "GitHub Actions",
          "Automated tests",
          "Build",
          "Docker image",
          "Security scan",
          "Deployment",
          "Environment management",
          "Rollback",
          "Release strategy",
        ],
      },
      {
        type: "module",
        title: "LLMOps",
        topics: [
          "Prompt versioning",
          "Model versioning",
          "Evaluation",
          "Tracing",
          "Token monitoring",
          "Cost monitoring",
          "Latency",
          "Model routing",
          "Guardrails",
          "AI regression",
          "Drift",
        ],
      },
      { type: "lab", number: 14, title: "Full Northstar Deployment" },
    ],
  },
  {
    title: "System Design at Scale",
    items: [
      {
        type: "module",
        title: "System Design",
        topics: [
          "Scalability",
          "Availability",
          "Load Balancing",
          "Caching",
          "Asynchronous Processing",
          "Distributed Systems",
          "API Reliability",
          "Fault Tolerance",
          "Architecture Trade-offs",
        ],
      },
      {
        type: "module",
        title: "Database Scaling",
        topics: [
          "Read replicas",
          "Sharding",
          "Partitioning",
          "Indexing",
          "Database bottlenecks",
          "Distributed databases",
        ],
      },
      {
        type: "module",
        title: "Distributed Systems",
        topics: ["Distributed Identities", "Message Guarantees", "Distributed Transactions"],
      },
      {
        type: "module",
        title: "Microservices",
        topics: ["Architecture Evolution", "Service Design", "Reliability", "Architecture Decisions"],
      },
      {
        type: "module",
        title: "AI at Scale",
        topics: [
          "Model gateways",
          "Model routing",
          "GPU capacity",
          "Inference scaling",
          "AI caching",
          "Batch inference",
          "Canary model releases",
          "AI drift",
          "AI reliability",
        ],
      },
      { type: "lab", number: 14, title: "Northstar Black Friday" },
    ],
  },
  {
    title: "Security, Reliability & Governance",
    items: [
      {
        type: "module",
        title: "Application Security",
        topics: [
          "OWASP Top 10",
          "Authentication",
          "Authorization",
          "RBAC",
          "Secrets",
          "API security",
          "Input validation",
          "Data protection",
        ],
      },
      {
        type: "module",
        title: "AI Security Review & Agent Governance",
        topics: ["Indirect injection", "Excessive agency", "Tool abuse", "Secure RAG", "Agent permissions"],
      },
      {
        type: "module",
        title: "SRE & Reliability",
        topics: [
          "SLAs",
          "SLOs",
          "SLIs",
          "Availability",
          "Reliability",
          "Disaster recovery",
          "Backups",
          "Incident management",
          "Postmortems",
        ],
      },
      {
        type: "module",
        title: "Incident Response",
        topics: [
          "Incident detection",
          "Severity",
          "Incident commander",
          "Communication",
          "Mitigation",
          "Root-cause analysis",
          "Recovery",
          "Postmortem",
          "Prevention",
        ],
      },
      { type: "lab", number: 15, title: "Northstar Red Team" },
      { type: "lab", number: 16, title: "Production Incident Room" },
      { type: "lab", number: 17, title: "Client Discovery" },
    ],
  },
  {
    title: "The FDE Craft",
    items: [
      {
        type: "module",
        title: "Technical Discovery",
        topics: [
          "Discovery frameworks",
          "Stakeholder interviews",
          "Business process mapping",
          "Technical discovery",
          "System discovery",
          "Data discovery",
          "Constraint discovery",
          "Success metrics",
        ],
      },
      {
        type: "module",
        title: "Problem Framing",
        topics: [
          "Problem statement",
          "User personas",
          "Current state",
          "Future state",
          "Pain points",
          "Requirements",
          "Assumptions",
          "Constraints",
          "Risks",
          "Success metrics",
        ],
      },
      { type: "lab", number: 18, title: "From Ambiguity to PRD" },
      {
        type: "module",
        title: "Solution Architecture",
        topics: [
          "Architecture diagrams",
          "Data flows",
          "Sequence diagrams",
          "API architecture",
          "AI architecture",
          "Security architecture",
          "Infrastructure architecture",
          "ADRs",
          "Technology selection",
        ],
      },
      { type: "lab", number: 19, title: "Architecture Defense" },
      {
        type: "module",
        title: "Scope & SOW",
        topics: [
          "POC",
          "Prototype",
          "MVP",
          "Production",
          "Scope definition",
          "Milestones",
          "Dependencies",
          "Estimates",
          "Risks",
          "Statement of Work",
          "Acceptance criteria",
        ],
      },
      { type: "lab", number: 20, title: "Write a Statement of Work" },
      {
        type: "module",
        title: "Customer Communication",
        topics: [
          "Technical communication",
          "Executive communication",
          "Architecture presentation",
          "Demo",
          "Incident communication",
          "Stakeholder updates",
          "Expectation management",
          "Scope negotiation",
          "Handling objections",
          "Explaining AI limitations",
        ],
      },
      { type: "lab", number: 21, title: "Run the Room" },
      {
        type: "module",
        title: "Business Value & ROI",
        topics: [
          "Business KPIs",
          "Technical KPIs",
          "Baseline",
          "Target",
          "ROI",
          "Cost savings",
          "Time savings",
          "Revenue impact",
          "Productivity",
          "Error reduction",
          "Adoption",
        ],
      },
      { type: "lab", number: 22, title: "ROI Business Case" },
      {
        type: "module",
        title: "Adoption & Handoff",
        topics: [
          "UAT",
          "User training",
          "Documentation",
          "Operational handoff",
          "Change management",
          "Adoption measurement",
          "Support model",
          "Knowledge transfer",
          "Post-deployment roadmap",
        ],
      },
      { type: "lab", number: 23, title: "Customer Handoff" },
      {
        type: "module",
        title: "Discovery & Design",
        topics: ["Discover", "Define", "Design", "Deliverables"],
      },
      {
        type: "module",
        title: "Build & Deploy",
        topics: [
          "Backend",
          "Frontend",
          "AI",
          "RAG",
          "Agent",
          "Integration",
          "Dockerize",
          "Deploy",
          "Monitor",
          "Evaluate",
          "Secure",
        ],
      },
    ],
  },
];
